helmDefaults:
  createNamespace: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

templates:
  default: &default
    namespace: besu-explorer
    valuesTemplate:
      - namespace: '{{`{{ .Release.Namespace }}`}}'

releases:
  - name: besu
    <<: *default
    chart: ./charts/besu-node
    wait: true
      
  - name: ingress-nginx
    <<: *default
    chart: ingress-nginx/ingress-nginx

  - name: ethereum-lite-explorer
    <<: *default
    chart: ./charts/alethio-lite-explorer
        
    needs:
      - besu-explorer/besu-node
      - besu-explorer/ingress-nginx
