helmDefaults:
  createNamespace: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

templates:
  default: &default
    namespace: besu
    valuesTemplate:
      - namespace: '{{`{{ .Release.Namespace }}`}}'

releases:
  - name: node
    <<: *default
    chart: ./charts/besu-node
    wait: true
    values:
      - resources:
          memRequest: 500m
      - config:
          network: "goerli" 
      - fullnameOverride: "besu-goerli-node"

  - name: ingress-nginx
    <<: *default
    chart: ingress-nginx/ingress-nginx

  - name: explorer
    <<: *default
    chart: ./charts/alethio-lite-explorer
    values:
      - config:
          appNode:
            serviceName: "besu-goerli-node"
    needs:
      - besu/node
      - besu/ingress-nginx
