{{- if .Values.ingress.enabled -}}
{{- $fullName := include "alethio-lite-explorer.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "alethio-lite-explorer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "alethio-lite-explorer.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
