apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu.fullname" . }}-toml-config
  labels:
    {{- include "besu.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
data:
  config.toml: |-
    # Node Information
    network={{ .Values.config.network | quote }}
    data-path={{ .Values.config.dataPath | quote }}
    logging={{ .Values.config.logging | quote }}

    {{- range $key, $val := .Values.config.extra }}
    {{ $key }}={{ $val }}
    {{- end }}

    {{- if .Values.config.p2p.enabled }}
    # P2P network
    p2p-enabled={{ .Values.config.p2p.enabled }}
    discovery-enabled={{ .Values.config.p2p.discovery }}
    p2p-host={{ .Values.config.p2p.host | quote }}
    p2p-port={{ .Values.config.p2p.port }}
    max-peers={{ .Values.config.p2p.maxPeers }}
    {{- end -}}

    {{ if or .Values.config.rpc.enabled .Values.config.graphql.enabled .Values.config.ws.enabled }}
    host-allowlist={{ .Values.config.http.allowlist }}
    {{ end }}

    {{- if .Values.config.rpc.enabled }}
    # JSON-RPC
    rpc-http-enabled={{ .Values.config.rpc.enabled }}
    rpc-http-host={{ .Values.config.rpc.host | quote }}
    rpc-http-port={{ .Values.config.rpc.port }}
    rpc-http-api={{ .Values.config.rpc.api }}
    rpc-http-cors-origins={{ .Values.config.rpc.corsOrigins }}
    rpc-http-authentication-enabled={{ .Values.config.rpc.authenticationEnabled }}
    {{ end }}

    {{- if .Values.config.graphql.enabled }}
    # GRAPHQL-RPC
    graphql-http-enabled={{ .Values.config.graphql.enabled }}
    graphql-http-host={{ .Values.config.graphql.host | quote }}
    graphql-http-port={{ .Values.config.graphql.port }}
    graphql-http-cors-origins={{ .Values.config.graphql.corsOrigins }}
    {{ end }}

    {{- if .Values.config.ws.enabled }}
    # WebSockets API
    rpc-ws-enabled={{ .Values.config.ws.enabled }}
    rpc-ws-host={{ .Values.config.ws.host | quote }}
    rpc-ws-port={{ .Values.config.ws.port }}
    rpc-ws-api={{ .Values.config.ws.api }}
    #rpc-ws-apis=["DEBUG","ETH"]
    rpc-ws-authentication-enabled={{ .Values.config.ws.authenticationEnabled }}
    {{ end }}
